const { chromium } = require('@playwright/test');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  await page.goto('https://parabank.parasoft.com/parabank/index.htm');
  await page.locator("//div[@id='loginPanel']/p[2]/a").click();
  const username = 'webuser' + Date.now();
  const password = 'Password123!';
  await page.locator("input[name='customer.firstName']").fill('Web');
  await page.locator("input[name='customer.lastName']").fill('Smoke');
  await page.locator("input[name='customer.address.street']").fill('1 Test Street');
  await page.locator("input[name='customer.address.city']").fill('Sydney');
  await page.locator("input[name='customer.address.state']").fill('NSW');
  await page.locator("input[name='customer.address.zipCode']").fill('2000');
  await page.locator("input[name='customer.phoneNumber']").fill('0400000000');
  await page.locator("input[name='customer.ssn']").fill('123456789');
  await page.locator("input[name='customer.username']").fill(username);
  await page.locator("input[name='customer.password']").fill(password);
  await page.locator("input[name='repeatedPassword']").fill(password);
  await page.getByRole('button', { name: /register/i }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: /open new account/i }).click();
  await page.locator('select').first().selectOption({ label: 'SAVINGS' });
  await page.getByRole('button', { name: /open new account/i }).click();
  await page.waitForTimeout(2000);
  const text = await page.locator('body').innerText();
  console.log('Account Opened visible:', /Account Opened!/i.test(text));
  await page.getByRole('link', { name: /accounts overview/i }).click();
  await page.waitForTimeout(1500);
  const overviewText = await page.locator('#accountTable').innerText();
  console.log('Overview visible:', /Accounts Overview/i.test(overviewText));
  console.log('Table contains money values:', /\$\d+\.\d{2}/.test(overviewText));
  console.log('Overview snippet:', overviewText.slice(0, 500));
  await browser.close();
})();
