const { chromium } = require('@playwright/test');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  await page.goto('https://parabank.parasoft.com/parabank/index.htm');
  await page.locator("//div[@id='loginPanel']/p[2]/a").click();
  await page.locator('input[name="customer.firstName"]').fill('Web');
  await page.locator('input[name="customer.lastName"]').fill('Smoke');
  await page.locator('input[name="customer.address.street"]').fill('1 Test Street');
  await page.locator('input[name="customer.address.city"]').fill('Sydney');
  await page.locator('input[name="customer.address.state"]').fill('NSW');
  await page.locator('input[name="customer.address.zipCode"]').fill('2000');
  await page.locator('input[name="customer.phoneNumber"]').fill('0400000000');
  await page.locator('input[name="customer.ssn"]').fill('123456789');
  const username = 'webuser' + Date.now();
  const password = 'Password123!';
  await page.locator('input[name="customer.username"]').fill(username);
  await page.locator('input[name="customer.password"]').fill(password);
  await page.locator('input[name="repeatedPassword"]').fill(password);
  await page.getByRole('button', { name: /register/i }).click();
  await page.waitForURL(/.*overview\.htm/);
  console.log('after-register-url', page.url());
  await page.getByRole('link', { name: /log out/i }).click();
  console.log('after-logout-url', page.url());
  await page.goBack();
  console.log('after-back-url', page.url());
  const bodyText = await page.locator('body').innerText();
  console.log('body-text', JSON.stringify(bodyText.slice(0, 500)));
  await browser.close();
})();
